name: ml-course
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - jupyterlab
  - ipykernel
  - ipywidgets
  - nodejs  # required for JupyterLab extensions

  - pip:
    - -r requirements.txt
